/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated/parent'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher/index'
import { Route as AuthenticatedParentIndexRouteImport } from './routes/_authenticated/parent/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedTeacherStudentsRouteImport } from './routes/_authenticated/teacher/students'
import { Route as AuthenticatedTeacherHomeworkRouteImport } from './routes/_authenticated/teacher/homework'
import { Route as AuthenticatedTeacherAiRouteImport } from './routes/_authenticated/teacher/ai'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSubjectsRouteImport } from './routes/_authenticated/admin/subjects'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminClassesRouteImport } from './routes/_authenticated/admin/classes'
import { Route as AuthenticatedTeacherStudentsStudentIdAiRouteImport } from './routes/_authenticated/teacher/students.$studentId.ai'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedParentIndexRoute =
  AuthenticatedParentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedTeacherStudentsRoute =
  AuthenticatedTeacherStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherHomeworkRoute =
  AuthenticatedTeacherHomeworkRouteImport.update({
    id: '/homework',
    path: '/homework',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherAiRoute = AuthenticatedTeacherAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedTeacherRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSubjectsRoute =
  AuthenticatedAdminSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClassesRoute =
  AuthenticatedAdminClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedTeacherStudentsStudentIdAiRoute =
  AuthenticatedTeacherStudentsStudentIdAiRouteImport.update({
    id: '/$studentId/ai',
    path: '/$studentId/ai',
    getParentRoute: () => AuthenticatedTeacherStudentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/parent': typeof AuthenticatedParentRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/teacher/ai': typeof AuthenticatedTeacherAiRoute
  '/teacher/homework': typeof AuthenticatedTeacherHomeworkRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/parent/': typeof AuthenticatedParentIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/teacher/students/$studentId/ai': typeof AuthenticatedTeacherStudentsStudentIdAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/teacher/ai': typeof AuthenticatedTeacherAiRoute
  '/teacher/homework': typeof AuthenticatedTeacherHomeworkRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/parent': typeof AuthenticatedParentIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/teacher/students/$studentId/ai': typeof AuthenticatedTeacherStudentsStudentIdAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/parent': typeof AuthenticatedParentRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/_authenticated/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/teacher/ai': typeof AuthenticatedTeacherAiRoute
  '/_authenticated/teacher/homework': typeof AuthenticatedTeacherHomeworkRoute
  '/_authenticated/teacher/students': typeof AuthenticatedTeacherStudentsRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/parent/': typeof AuthenticatedParentIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/teacher/students/$studentId/ai': typeof AuthenticatedTeacherStudentsStudentIdAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/parent'
    | '/teacher'
    | '/admin/classes'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/users'
    | '/teacher/ai'
    | '/teacher/homework'
    | '/teacher/students'
    | '/admin/'
    | '/parent/'
    | '/teacher/'
    | '/teacher/students/$studentId/ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/classes'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/users'
    | '/teacher/ai'
    | '/teacher/homework'
    | '/teacher/students'
    | '/admin'
    | '/parent'
    | '/teacher'
    | '/teacher/students/$studentId/ai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/parent'
    | '/_authenticated/teacher'
    | '/_authenticated/admin/classes'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/subjects'
    | '/_authenticated/admin/users'
    | '/_authenticated/teacher/ai'
    | '/_authenticated/teacher/homework'
    | '/_authenticated/teacher/students'
    | '/_authenticated/admin/'
    | '/_authenticated/parent/'
    | '/_authenticated/teacher/'
    | '/_authenticated/teacher/students/$studentId/ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/parent/': {
      id: '/_authenticated/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof AuthenticatedParentIndexRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/teacher/students': {
      id: '/_authenticated/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/homework': {
      id: '/_authenticated/teacher/homework'
      path: '/homework'
      fullPath: '/teacher/homework'
      preLoaderRoute: typeof AuthenticatedTeacherHomeworkRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/ai': {
      id: '/_authenticated/teacher/ai'
      path: '/ai'
      fullPath: '/teacher/ai'
      preLoaderRoute: typeof AuthenticatedTeacherAiRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subjects': {
      id: '/_authenticated/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/classes': {
      id: '/_authenticated/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AuthenticatedAdminClassesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/teacher/students/$studentId/ai': {
      id: '/_authenticated/teacher/students/$studentId/ai'
      path: '/$studentId/ai'
      fullPath: '/teacher/students/$studentId/ai'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsStudentIdAiRouteImport
      parentRoute: typeof AuthenticatedTeacherStudentsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClassesRoute: typeof AuthenticatedAdminClassesRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminSubjectsRoute: typeof AuthenticatedAdminSubjectsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClassesRoute: AuthenticatedAdminClassesRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminSubjectsRoute: AuthenticatedAdminSubjectsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedParentRouteChildren {
  AuthenticatedParentIndexRoute: typeof AuthenticatedParentIndexRoute
}

const AuthenticatedParentRouteChildren: AuthenticatedParentRouteChildren = {
  AuthenticatedParentIndexRoute: AuthenticatedParentIndexRoute,
}

const AuthenticatedParentRouteWithChildren =
  AuthenticatedParentRoute._addFileChildren(AuthenticatedParentRouteChildren)

interface AuthenticatedTeacherStudentsRouteChildren {
  AuthenticatedTeacherStudentsStudentIdAiRoute: typeof AuthenticatedTeacherStudentsStudentIdAiRoute
}

const AuthenticatedTeacherStudentsRouteChildren: AuthenticatedTeacherStudentsRouteChildren =
  {
    AuthenticatedTeacherStudentsStudentIdAiRoute:
      AuthenticatedTeacherStudentsStudentIdAiRoute,
  }

const AuthenticatedTeacherStudentsRouteWithChildren =
  AuthenticatedTeacherStudentsRoute._addFileChildren(
    AuthenticatedTeacherStudentsRouteChildren,
  )

interface AuthenticatedTeacherRouteChildren {
  AuthenticatedTeacherAiRoute: typeof AuthenticatedTeacherAiRoute
  AuthenticatedTeacherHomeworkRoute: typeof AuthenticatedTeacherHomeworkRoute
  AuthenticatedTeacherStudentsRoute: typeof AuthenticatedTeacherStudentsRouteWithChildren
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
}

const AuthenticatedTeacherRouteChildren: AuthenticatedTeacherRouteChildren = {
  AuthenticatedTeacherAiRoute: AuthenticatedTeacherAiRoute,
  AuthenticatedTeacherHomeworkRoute: AuthenticatedTeacherHomeworkRoute,
  AuthenticatedTeacherStudentsRoute:
    AuthenticatedTeacherStudentsRouteWithChildren,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
}

const AuthenticatedTeacherRouteWithChildren =
  AuthenticatedTeacherRoute._addFileChildren(AuthenticatedTeacherRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedParentRoute: typeof AuthenticatedParentRouteWithChildren
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedParentRoute: AuthenticatedParentRouteWithChildren,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
